apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-volume-freezer-apiserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-volume-freezer
        component: apiserver
    spec:
      containers:
      - name: apiserver
        image: wikiwi/kube-volume-freezer:0.1.0
        command: ['kvf-apiserver']
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: KVF_TOKEN
          valueFrom:
            secretKeyRef:
              name: kube-volume-freezer-secret
              key: apiserver-token
        - name: KVF_MINION_TOKEN
          valueFrom:
            secretKeyRef:
              name: kube-volume-freezer-secret
              key: minion-token
        - name: KVF_MINION_SELECTOR
          value: "app=kube-volume-freezer,component=minion"
        - name: KVF_MINION_PORT
          value: "8080"
        - name: KVF_MINION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

